### ISSUE TITLE
Unable to recover wallet with 12 words.

### ISSUE THREAD

**Issue by jpesant** [Kiirocoin/kiiro#14]
Since v1.0.0.4, my Android wallet is no longer recognized and I have to restore my wallet with my 12 words. Being impossible on the Android application to recover with only 12 words, I installed the application on Windows PC. However, knowing full well that I have the right sentence, my wallet is lost since my 12 words do not work. Being a programmer myself, I know this is the right combination and there definitely seems to be a problem retrieving a wallet with 12 words.

**Comment by Kiirocoin** [comment]
"Since v1.0.0.4, my Android wallet is no longer recognized and I have to restore my wallet with my 12 words."

There are many wallets for kiirocoin, remember QT Wallet is not Electrum wallet.

v1.0.0.4 is not an Android wallet but QT wallet. The android version of December 23 is 5.3.0.0.
In Android application until 5.3.0.0 use elctrum client, electrum client support different way to recover wallet, such 12/24 words, but in the version 5.3.0.0 the Android App is redesign left the electrum client support. Now is electrum free. The seed is stronger with 24 words.

Kiirocoin Electrum is available not only for Android, but also for Windows, Linux, Mac OS

There are different ways to recover a wallet for previous Android 5.3.0.0.
The simplest is download Electrum Client from kiirocoin.org website, recover your wallet with your old seed and then create a new wallet in Android wallet.
At this point, transfer the funds from the old electrum address to the new Android wallet.

It will be easy for a programmer to use this solution.

**Comment by Kiirocoin** [comment]
closed

**Comment by jpesant** [comment]
Thank you very much for your quick response and now I understand the
changes much better.

I installed Kiiro Electrum 5.3.0.0 but my connection status is still NOT
CONNECTED to the Electrum Network
